### ISSUE TITLE
doc: update calibration documentation

### ISSUE THREAD

**Issue by swishswish123** [SciKit-Surgery/scikit-surgerybard#114]
params in docs need updating to match the correct params.

In docs it says:
Use the ‘-s’ option to specify a directory to save to, and the ‘-p’ option to specify a filename prefix.

Doing this gives this error:
    source = vcu.validate_camera_source(source)
  File "/Users/aure/miniconda3/envs/BARD/lib/python3.7/site-packages/sksurgeryutils/utils/opencv_video_capture_utils.py", line 35, in validate_camera_source
    raise RuntimeError("OpenCV source is a string, but not a file.")
RuntimeError: OpenCV source is a string, but not a file.

the reason being that the params are the following:
-s is the openCV source (eg. 0 for webcam)
-o for output 
-p was correct (prefix
(-ni not mentioned was for non-interactive mode)

**Comment by mxochicale** [comment]
Hi @swishswish123 

just fixed this one with the following changes: 
![Screenshot from 2023-06-23 08-24-16](https://github.com/SciKit-Surgery/scikit-surgerybard/assets/11370681/4060b27a-3515-4d73-89b3-14c683273352)

Feel free to re-open it if there is something missing. Cheers,--Miguel
