### ISSUE TITLE
The use of chessboard pattern on pillars in BARD demo

### ISSUE THREAD

**Issue by rohang1411** [SciKit-Surgery/scikit-surgerybard#82]
The image below shows the setup of BARD. Found this image in doc folder.

![image](https://user-images.githubusercontent.com/51371041/148543271-8795dd07-b846-4375-8b7b-4a7474c80e87.png)

There are the few things which I can observe -

1. Laid out Chessboard pattern - I think it's for camera calibration.
2. Chessboard pattern on pillars - Not sure what's that for?
3. Aruco tags (Both the tags) - For tracking and overlaying the model

Can you please clarify the role of chessboard pattern on pillars.

**Comment by thompson318** [comment]
Hello, I'm afraid the various chessboards have no role in the BARD demo. This pelvis phantom dates back to my [PhD Thesis](https://discovery.ucl.ac.uk/id/eprint/1475351/1/thesis_thompson.pdf), which I made long before BARD. I thought at the time it would be useful to have multiple marker patterns for measuring accuracy, but in the end I don't think I used them.
The only things used in the BARD demo are the two ArUco tag patterns, one stuck to the phantom and the other stuck to the pen/pointer. Then the pointer is used to perform point based registration using the fiducial markers (the browny/yellow things on top of some of the posts).
